version: '3.0'

services:
  redis:
    image: redis:6.2

  worker:
    build:
      context: ./
      dockerfile: Dockerfile
    image: runbox:latest
    env_file:
      - .env
    volumes:
      - ./:/code
    working_dir: /code
    user: root
    command: python -m celery -A tasker worker

  flower:
    build:
      context: ./
      dockerfile: Dockerfile
    image: runbox:latest
    env_file:
      - .env
    ports:
      - 5555:5555
    volumes:
      - ./:/code
    working_dir: /code
    user: root
    command: python -m celery -A tasker flower
